import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DashboardHeader } from "@/components/DashboardHeader";
import { SidebarWrapper } from "@/components/SidebarWrapper";
import { ProductProvider } from "@/context/product.context";
import { CartProvider } from "@/context/cart.context";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <CartProvider>
          <ProductProvider>
            <SidebarWrapper />
            <main className="flex-1 h-screen overflow-y-auto bg-[#EFEDE7]">
              <DashboardHeader />
              {children}
            </main>
            <Toaster position="top-center" reverseOrder={false} />
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
